SUN397:
    dataset_parser: image_cls
    dataset_name: SUN397
    dataset_split: test
    image_root: /home/xuanmingcui/datasets/MMEB-eval/eval_images/
    eval_type: local
OK-VQA:
    dataset_parser: image_qa
    dataset_name: OK-VQA
    dataset_split: test
    image_root: /home/xuanmingcui/datasets/MMEB-eval/eval_images/
    eval_type: local
CIRR:
    dataset_parser: image_i2i_vg
    dataset_name: CIRR
    dataset_split: test
    image_root: /home/xuanmingcui/datasets/MMEB-eval/eval_images/
    eval_type: local
MSCOCO:
    dataset_parser: image_i2i_vg
    dataset_name: MSCOCO
    dataset_split: test
    image_root: /home/xuanmingcui/datasets/MMEB-eval/eval_images/
    eval_type: local